version: '3.8'

services:

  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - .:/app
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_reverse_proxy"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.services.benji_cv.loadbalancer.server.port=3000"
        - "traefik.http.routers.benji_cv.entrypoints=web"
        - "traefik.http.routers.benji_cv.rule=Host(`my_host`)"
        - "traefik.http.routers.benji_cv-secured.entrypoints=websecured"
        - "traefik.http.routers.benji_cv-secured.rule=Host(`my_host`)"
        - "traefik.http.routers.benji_cv-secured.tls=true"
        - "traefik.http.routers.benji_cv-secured.tls.certresolver=letsencrypt"
    networks:
      - traefik_reverse_proxy

networks:
  traefik_reverse_proxy:
    external: true
